opt_in_rules:
    - fatal_error_message
    - force_unwrapping
        
disabled_rules:
    - file_length
    - line_length
    - multiple_closures_with_trailing_closure

excluded:
    - Pods
    - Carthage
    - "*Tests/*"
